### ISSUE TITLE
The release ZIP file is corrupt

### ISSUE THREAD

**Issue by JoakimCh** [Falconne/HeatMap#11]
Try to open it using Linux and you'll see filenames with \ inside them instead of getting the proper folder structure. I had to resort to StackExchange to find a fix:
https://unix.stackexchange.com/a/375846/275234

Solution:
You should use a better program for compressing the files (one without this bug), maybe 7-Zip.

**Comment by Falconne** [comment]
Thanks, will take a look

**Comment by Falconne** [comment]
Build script and release has been updated
