### ISSUE TITLE
Temperature widget gets hidden behind the "learning helper" window

### ISSUE THREAD

**Issue by ChrisF-127** [Falconne/HeatMap#22]
As the "learning helper" is a window, setting the widget to be in front will require some rework as to how it is drawn, as far as I can tell. 
Making the widget into a window does allow for setting it to the "top-most" layer, that way it can be moved in front of the helper.
Unsure yet of potential side-effects and need to figure out how to properly draw the widget as a window.

If all fails, it might be easier to just move it over when the helper is active, in a similar fashion as was done before it was made movable and maybe limit the right-most position so it can't be moved under the helper when it's active.

**Comment by Falconne** [comment]
I would prefer the widget not be in front of the learning helper. If it ends up on top of the helper for some reason and the person doesn't know they can move the widget, they'll log it as a bug.

On a side note, just had the thought that the tooltip on the widget should be updated to say you can move it with Shift-Click.

I think it should be enough that if the helper is enabled and the current widget position overlaps with it, the mod should move the widget to the side or under the helper. This should happen even if the user deliberately moves the widget over the helper (there's no functional reason why anyone would want either of these on top of the other).

**Comment by ChrisF-127** [comment]
Alright, that should be easier to implement. 

The tooltip should already say that it can be moved, but it doesn't say yet that the moving can be locked via the settings, so that needs to be added.

**Comment by ChrisF-127** [comment]
@Falconne The update is complete, but from what I gathered, it seems like only you as the author can push it to the workshop.
Even as a contributor, apparently all I can do is modify the mod's workshop page, unless I'm missing something.

**Comment by Falconne** [comment]
Thanks for sorting that. Oh that's annoying about the workshop. I've published the new version now, I'll let you add a comment about the update.

Also I realised I forgot to push a version bump in the last set of changes, so I've pushed an update to AssemblyVersion to take it to build 1.3.18.

For the people who don't use Steam, can you also create a new release on Github https://github.com/Falconne/HeatMap/releases in the style of the previous? You'll need to pull my latest change and do another local build, then you can upload the zip that gets created in the dist directory into the release.
