### ISSUE TITLE
[Bug] Weird heatmap overlay

### ISSUE THREAD

**Issue by ErnestUTN** [Falconne/HeatMap#8]
I dunno how it happened but for some reason the heatmap overlay screwed up and it shows like this... The only suspect I can think of is the fact I turned it on in a caravan map.. but I am not sure:

![image](https://user-images.githubusercontent.com/8976434/48873416-811be380-edcc-11e8-8599-0137076c31e4.png)

Turning it on and off doesn't fix it.. Ill try reloading the savegame..

EDIT: Reloading the game fixed it!.

**Comment by Falconne** [comment]
That's weird but it's probably an interaction with another mod. I'll close this for now as it's not possible to find investigate, but if you find a way to reliably reproduce it you can re-open with the steps.

**Comment by ErnestUTN** [comment]
It happened again. specifically after turning it on while setting up a camp with a caravan

1- Create a caravan and go somewhere where a new map would load (mineral veins, ambush, quest mission, etc)
2- Press the HeatMap toggle widget
3- SOmething happens (It might pause your game and won't enable you to unpause until you switch to your main base camp for example
4- If you try to turn on the heatmap in your main base, it is screwed like in the OP

----
To fix:
1- Try Save the game while in the main base
2- Load the game and turn on the heatmap
3- It should fix it, but you still can't use the heatmap in other colonies.

**Comment by Falconne** [comment]
Should be fixed with latest update
